language: ruby
bundler_args: --quiet
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.3.0
  - ruby-head
script: "bundle exec rake"
gemfile:
  - Gemfile
notifications:
  recipients:
    - lourens@bearmetal.eu
branches:
  only:
    - master